feat: Rework ./deploy to run 'learn-ocaml build' within docker

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,45 +1,119 @@
-#!/bin/bash
-# Erik Martin-Dorel, 2018
+#!/usr/bin/env bash
+# Erik Martin-Dorel - 2018, 2020
 
 set -e # exit on failure
+srcdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
+
+# TODO: make this value configurable?
+image="ocamlsf/learn-ocaml:master"
 
 pause() {
     read -r -s -n 1 -p "Press any key to ${1:-continue} (or ^C to exit)... "
     echo
 }
 
-srcdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
-repo="learn-ocaml"
+get_url() {
+    # if origin = git@github.com:pfitaxel/pfitaxel-demo.git
+    # or origin = https://github.com/pfitaxel/pfitaxel-demo.git
+    # will return: https://pfitaxel.github.io/pfitaxel-demo
+    local remote
+    remote=$(git remote get-url origin)
+    remote=${remote#https://*/}
+    remote=${remote##*:}
+    orga=${remote%/*}
+    repo=${remote##*/}
+    repo=${repo%.git}
+    echo "https://$orga.github.io/$repo"
+}
+# test: get_url git@github.com:pfitaxel/pfitaxel-demo.git
+# test: get_url https://github.com/pfitaxel/pfitaxel-demo.git
 
-if [ "$1" != "-B" ]; then
-    cat >&2 <<EOF
-Usage: ${BASH_SOURCE[0]} [-B]  # where -B runs 'make clean' beforehand
+clone_subdir() {
+    local repo="learn-ocaml"
+    if test -d "${srcdir}/.build/$repo"; then
+        pushd "${srcdir}/.build/$repo"
+        git fetch --depth=1 origin
+        git reset --hard "@{u}"
+    else
+        git clone https://github.com/ocaml-sf/learn-ocaml.git -b master --depth=1 "${srcdir}/.build/$repo"
+        pushd "${srcdir}/.build/$repo"
+    fi
+    popd
+}
+
+# deprecated function
+make_gen() {
+    local target_url="$1"
+    local repo="learn-ocaml"
+    pushd "${srcdir}/.build/$repo"
+    if [ "$2" = "-B" ]; then
+        make clean
+    fi
+    if [ "$1" != "-B" ]; then
+            cat >&2 <<EOF
+        Usage: make_gen [-B]  # where -B runs 'make clean' beforehand
 EOF
-fi
+    fi
+    # REMARK: needs an opam switch (opam install, etc.)
+    export PS4='+ \e[36;1m(${0##*/} @ line $LINENO) \$\e[0m '
+    set -x # trace for debug
+    # make build
+    # make process-repo
+    make
+    make opaminstall
+    learn-ocaml build --root "$target_url" --repo=demo-repository
+    rsync -av --delete-delay www/ "${srcdir}/docs"
+    git describe --long --always > "${srcdir}/VERSION"
+    popd
+}
 
-export PS4='+ \e[36;1m(${0##*/} @ line $LINENO) \$\e[0m '
-set -x # trace for debug
+function failtemp () {
+    echo "Failed to create a temporary directory. Please report." >&2
+    exit 1
+}
 
-if test -d "${srcdir}/.build/$repo"; then
-    cd "${srcdir}/.build/$repo"
-    git fetch --depth=1 origin
-    git reset --hard @{u}
-else
-    git clone https://github.com/agrn/learn-ocaml.git -b ag/static-deployment --depth=1 "${srcdir}/.build/$repo"
-    cd "${srcdir}/.build/$repo"
-fi
-# TODO: run "opam install" etc. (or leverage the build using Docker)
-[ "$1" = "-B" ] && make clean
-# make build
-# make process-repo
-make
-make opaminstall
-learn-ocaml build --root "https://pfitaxel.github.io/pfitaxel-demo-dev" --repo=demo-repository
-rsync -av --delete-delay www/ "${srcdir}"/docs
-descr=$(git describe --long --always)
+docker_gen() {
+    local target_url="$1"
+    local repo="learn-ocaml"
+    export PS4='+ \e[36;1m(${0##*/} @ line $LINENO) \$\e[0m '
+    set -x # trace for debug
+    : Create temporary directory...
+    T=$(mktemp -d /tmp/learn-ocaml-www.XXX) || failtemp
+    : Generate www using Docker...
+    sudo docker run --rm -i -v "${srcdir}/.build/$repo/demo-repository:/repository" -v "$T:/home/learn-ocaml/tmp" --entrypoint="" "$image" sh -c "learn-ocaml build --repo=/repository --root $target_url && mv -v www tmp/"
+    # : Replace docs folder...
+    # rm -fr docs/
+    # mv -v -T "$T/www" ./docs
+    # rmdir "$T"
+    # : Mostly equivalent to:
+    rsync -av --delete-delay "$T/www/" "${srcdir}/docs"
+    : Remove temporary directory...
+    rm -fr "$T"
+    echo "$image" > VERSION
+}
 
-cd "${srcdir}"
-cp -pv .nojekyll docs/
-git add -v -A docs
-git commit -m "Build $repo ($descr)" -e
-pause push && git push
+deploy_locally() {
+    clone_subdir
+    port="8080"
+    target_url="http://localhost:$port"
+    docker_gen "$target_url"
+    cp -pv "${srcdir}/.nojekyll" "${srcdir}/docs/"
+
+    python3 -m http.server -d "${srcdir}/docs" "$port"
+}
+
+deploy() {
+    clone_subdir
+    target_url=$(get_url)
+    docker_gen "$target_url"
+    cp -pv "${srcdir}/.nojekyll" "${srcdir}/docs/"
+
+    cd "${srcdir}"
+    git add -v -A docs
+    repo="learn-ocaml"
+    git commit -m "Build $repo ($(<VERSION))" -e
+    pause push && git push
+}
+
+# deploy_locally
+deploy
